name: Create Production Builds

on:
  push:
    branches: ['beta']

jobs:
  build_android:
    name: Build Android
    type: build # This job type creates a production build for Android
    params:
      platform: android
      profile: production
